include:
  - services.compose.yml

services:
  http-entrypoint:
    image: docker.io/library/caddy:latest
    restart: always
    cap_add:
      - NET_ADMIN
    configs:
      - source: caddy
        target: /etc/caddy/Caddyfile
    ports:
      - 8000:80

  db:
    image: timescale/timescaledb-ha:pg16.4-ts2.16.1-all
    restart: always
    hostname: db
    user: root
    volumes:
      - db-data:/home/postgres/pgdata/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - POSTGRES_DB=wisdom
    secrets:
      - postgres-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--dbname=wisdom"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  redis:
    image: docker.io/library/redis:alpine
    restart: always
    hostname: redis
    command: --save 30 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli | grep PONG"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
  
  frontend:
    build:
      context: https://github.com/wisdom-oss/frontend-workspace.git#${FRONTEND_BRANCH:-main}
      dockerfile: Dockerfile
      args:
        - OIDC_AUTHORITY=${OIDC_ISSUER:?OpenID Connect Issuer is not configured}
        - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:?OpenID Connect Client ID is not configured}
    hostname: frontend
    restart: always

  backend:
    image: traefik:v3.1
    hostname: backend
    container_name: traefik
    command: 
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
configs:
  caddy:
    file: ./configs/Caddyfile

secrets:
  postgres-password:
    file: ./.pgpass
    
volumes:
  db-data:
    name: wisdom-db