version: '3.8'

# Named volumes
volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  redis_persistence:

# Networking Setup
networks:
  default:
    name: wisdom-oss
    driver: bridge

# Base Services for using the Product
services:
  reverse-proxy:
    stop_grace_period: 1m
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  frontend:
    build: https://github.com/wisdom-oss/frontend-workspace.git#main
    image: wisdom-oss/frontend:main-latest
    stop_grace_period: 1m
    hostname: frontend
    restart: always
    depends_on:
      - api-gateway
      - reverse-proxy
    expose:
      - 80
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  message-broker:
    image: rabbitmq:3.9.9-management-alpine
    stop_grace_period: 1m
    restart: always
    hostname: message-broker
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=wisdom
      - RABBITMQ_DEFAULT_PASS=<<gen-pass-rabbitmq>>
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  postgres:
    image: postgis/postgis:14-master
    stop_grace_period: 1m
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=<<gen-postgres-pass>>
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5


  redis:
    image: redis:alpine
    stop_grace_period: 1m
    restart: always
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis_persistence:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass <<gen-redis-pass>>
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  service-registry:
    build: https://github.com/wisdom-oss/service-registry.git#main
    stop_grace_period: 1m
    image: wisdom-oss/service-registry:main-latest
    restart: always
    ports:
      - 8761:8761
    hostname: service-registry
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  api-gateway:
    build: https://github.com/wisdom-oss/api-gateway.git#main
    image: wisdom-oss/api-gateway:main-latest
    stop_grace_period: 1m
    restart: always
    hostname:
      api-gateway
    expose:
      - 8090
    depends_on:
      - service-registry
    environment:
      SERVICE_REGISTRY_HOST: service-registry
    volumes:
      - ./data/gateway:/opt/api-gateway/config
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  auth-service:
    build: https://github.com/wisdom-oss/authorization-service.git#main
    image: wisdom-oss/authorization-service:main-latest
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - postgres
      - service-registry
    expose:
      - 5000
    hostname: authorization-service
    environment:
      - CONFIG_SERVICE_NAME=authorization-service
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_SERVICE_REGISTRY_HOST=service-registry
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5
  
  T-auth-service:
    build: https://github.com/wisdom-oss/authorization-service.git#dev
    image: wisdom-oss/authorization-service:main-latest
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - postgres
      - service-registry
    expose:
      - 5000
    environment:
      - CONFIG_SERVICE_NAME=authorization-service
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_KONG_HOST=kong
      - CONFIG_KONG_ADMIN_PORT=8001
      - CONFIG_KONG_SERVICE_SLUG=auth
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  amqp-auth-service:
    build: https://github.com/wisdom-oss/amqp-authorization-service.git#main
    image: wisdom-oss/service-amqp-authorization:main-latest
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - postgres
      - message-broker
    hostname: amqp-authorization-service
    environment:
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_AMQP_DSN=amqp://wisdom:<<gen-pass-rabbitmq>>@message-broker/%2F?heartbeat=600
      - CONFIG_AMQP_BIND_EXCHANGE=authorization-service
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  usage-forecast-rest:
    build: https://github.com/wisdom-oss/service-water-usage-forecasts-rest.git#main
    image: wisdom-oss/water-usage-forecasts-rest:main-latest
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - message-broker
      - redis
      - service-registry
    expose:
     - 5000
    environment:
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_AMQP_DSN=amqp://wisdom:<<gen-pass-rabbitmq>>@message-broker/%2F
      - CONFIG_AMQP_EXCHANGE=water-usage-forecasts
      - CONFIG_SERVICE_REGISTRY_HOST=service-registry
      - CONFIG_SERVICE_NAME=water-usage-forecasts-rest
      - CONFIG_REDIS_DSN=redis://:<<gen-redis-pass>>@redis/0
      - CONFIG_USE_REDIS=true
    labels:
      - wisdom.oss.type=backend-service
      - wisdom.oss.protocol=AMQP,HTTP
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  usage-forecast-calculations:
    build: https://github.com/wisdom-oss/service-water-usage-forecasts.git#main
    image: wisdom-oss/water-usage-forecasts-calculations:main-latest
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - message-broker
      - postgres
    expose:
     - 5000
    environment:
      - CONFIG_AMQP_DSN=amqp://wisdom:<<gen-pass-rabbitmq>>@message-broker/%2F?heartbeat=1800
      - CONFIG_AMQP_BIND_EXCHANGE=water-usage-forecasts
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_SERVICE_NAME=water-usage-forecasts-calculations
    labels:
      - wisdom.oss.type=backend-service
      - wisdom.oss.protocol=AMQP
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  geodata-service:
    build: https://github.com/wisdom-oss/service-geo-data-rest.git#main
    image: wisdom-oss/services/geo-data-rest:main-latest
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - message-broker
      - postgres
      - service-registry
    expose:
      - 5000
    environment:
      - CONFIG_AMQP_DSN=amqp://wisdom:<<gen-pass-rabbitmq>>@message-broker/%2F
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_SERVICE_NAME=geodata-rest
      - CONFIG_SERVICE_REGISTRY_HOST=service-registry
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5

  consumers:
    build: https://github.com/wisdom-oss/service-consumers.git#main
    image: wisdom-oss/services/consumers:main
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - amqp-auth-service
      - message-broker
      - service-registry
      - postgres
    expose:
      - 5000
    environment:
      - CONFIG_AMQP_DSN=amqp://wisdom:<<gen-pass-rabbitmq>>@message-broker/%2F
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_SERVICE_NAME=consumers-rest
      - CONFIG_SERVICE_REGISTRY_HOST=service-registry 
      - CONFIG_REDIS_DSN=redis://:<<gen-redis-pass>>@redis/0

  water-rights:
    build: https://github.com/wisdom-oss/service-water-rights.git#main
    image: wisdom-oss/services/water-rights:main
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - amqp-auth-service
      - message-broker
      - service-registry
      - postgres
    expose:
      - 5000
    environment:
      - CONFIG_AMQP_DSN=amqp://wisdom:<<gen-pass-rabbitmq>>@message-broker/%2F
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_SERVICE_NAME=water-rights-rest
      - CONFIG_SERVICE_REGISTRY_HOST=service-registry 
      - CONFIG_REDIS_DSN=redis://:<<gen-redis-pass>>@redis/0


  water-usage-history:
    build: https://github.com/wisdom-oss/service-water-usage-history.git#main
    image: wisdom-oss/services/water-usage-history:main
    stop_grace_period: 1m
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - amqp-auth-service
      - message-broker
      - service-registry
      - postgres
    expose:
      - 5000
    environment:
      - CONFIG_AMQP_DSN=amqp://wisdom:<<gen-pass-rabbitmq>>@message-broker/%2F
      - CONFIG_DB_DSN=postgresql://postgres:<<gen-postgres-pass>>@postgres:5432/wisdom
      - CONFIG_SERVICE_NAME=water-usage-history
      - CONFIG_SERVICE_REGISTRY_HOST=service-registry 


  kong-gateway:
    image: kong/kong-gateway:2.8.0.0-alpine
    restart: always
    stop_grace_period: 1m
    hostname: kong-gateway
    depends_on:
      - postgres
    environment:
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=<<gen-postgres-pass>>
      - KONG_DATABASE=postgres
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 10001:8001
      - 8080:8000
